
# TODO: clean up names, and translate for German version.

# ID, slug, name, ???, ???, ???
#
# --> maybe add an individual description string to some.

COLOR_DATA = (
    (1, 'beige', 'beige'),
    (2, 'blue', 'blue'),
    (3, 'brown', 'brown'),
    (4, 'yellow', 'yellow'),
    (5, 'grey', 'grey'),
    (7, 'green', 'green'),
    (8, 'white', 'white'),
    (9, 'pink', 'pink'),
    (10, 'red', 'red'),
    (11, 'black', 'black'),
    (12, 'white', 'white'),
)
CLASSIFICATION_DATA = (
    (0, 'amazonite - granite', 'amazonite-granite'),
    (0, 'foidolite', 'foidolite'),
    (0, 'hornblende-amphibolite', 'hornblende-amphibolite'),
    (0, 'iron ore', 'iron ore'),
    (0, 'marble-onyx', 'marble-onyx'),
    (0, 'mikrolin-quatrz -phyllite', 'mikrolin-quatrz-phyllite'),
    (0, 'n/a', 'n/a'),
    (0, 'n.a', 'n/a'),
    (0, 'orbicular granite', 'orbicular granite'),
    (0, 'orthoklase - quartz - phyllite', 'orthoklase-quartz-phyllite'),
    (0, 'quartz -phyllite', 'quartz-phyllite'),
    (0, 'phyllite', 'phyllite'),
    (0, 'sodalite-syenite', 'sodalite-syenite'),
    (0, 'schist', 'schist'),
    (0, 'serizite-quatrz-phyllite', 'serizite-quatrz-phyllite'),
    (0, 'sodalithe-gneiss', 'sodalithe-gneiss'),
    (0, 'sodalithe-syenite', 'sodalithe-syenite'),
    (2, 'anhydrite', 'anhydrite'),
    (3, 'anorthosite', 'anorthosite'),
    (4, 'aplite', 'aplite'),
    (5, 'basalt', 'basalt'),
    (6, 'charnockite', 'charnockite'),
    (8, 'cordierite', 'cordierite'),
    (9, 'diabase', 'diabase'),
    (10, 'diorite', 'diorite'),
    (13, 'gabbro', 'gabbro'),
    (14, 'gneiss', 'gneiss'),
    (15, 'granite', 'granite'),
    (17, 'granodiorite', 'granodiorite'),
    (18, 'granulite', 'granulite'),
    (19, 'hornfels', 'hornfels'),
    (20, 'limestone', 'limestone'),
    (21, 'conglomerate', 'conglomerate'),
    (22, 'lamprophyre', 'lamprophyre'),
    (23, 'lava', 'lava'),
    (25, 'marble', 'marble'),
    (26, 'metatexite', 'metatexite'),
    (27, 'migmatite', 'migmatite'),
    (30, 'monzonite', 'monzonite'),
    (32, 'norite', 'norite'),
    (33, 'ophicalcite', 'ophicalcite'),
    (35, 'orthogneiss', 'orthogneiss'),
    (37, 'paragneiss', 'paragneiss'),
    (38, 'pegmatite', 'pegmatite'),
    (39, 'porphyry', 'porphyry'),
    (41, 'quartzite', 'quartzite'),
    (42, 'rhyolite', 'rhyolite'),
    (43, 'sandstone', 'sandstone'),
    (44, 'slate', 'slate'),
    (46, 'serpentinite', 'serpentinite'),
    (48, 'soapstone', 'soapstone'),
    (50, 'spessartite', 'spessartite'),
    (51, 'syenite', 'syenite'),
    (52, 'tonalite', 'tonalite'),
    (53, 'trachyte', 'trachyte'),
    (54, 'travertine', 'travertine'),
    (55, 'tuff', 'tuff'),
)
TEXTURE_DATA = (
    (0, 'coarse-grained', 'coars', ''),
    (0, 'coarse-grained', 'coarse'),
    (0, 'coarse-grained', 'Coarse'),
    (0, 'coarse-grained', 'coarse grain'),
    (0, 'coarse-grained', 'coarse grained'),
    (0, 'veined-coarse-grained', 'coarse grain, veined'),
    (0, 'fine-grained', 'fine'),
    (0, 'fine-grained', 'Fine'),
    (0, 'fine-grained', 'fine grain'),
    (0, 'fine-grained', 'fine grained'),
    (0, 'veined-fine-grained', 'fine grained, veined'),
    (0, 'fine-grained', 'fine grained, with plenty of large fossils'),
    (0, 'medium-grained', 'fine to medium'),
    (0, 'fine-grained', 'Fine grained'),
    (0, 'medium-grained', 'fine, medium'),
    (0, 'veined-fine-grained', 'fine, veined'),
    (0, 'veined', 'geädert'),
    (0, 'coarse-grained', 'grob'),
    (0, 'medium-grained', 'medium'),
    (0, 'medium-grained', 'Medium'),
    (0, 'medium-grained', 'medium grain'),
    (0, 'medium-grained', 'medium grained'),
    (0, 'medium-grained', 'medium - coarse grain'),
    (0, 'dunno', 'n/a'),
    (0, 'veined', 'veined'),
    (0, 'veined', 'Veined'),
)
COUNTRY_DATA = (
    (24, 'angola', 'Angola', ''),
    (32, 'argentina', 'Argentina', 'ar'),
    (36, 'australia', 'Australia', 'au'),
    (40, 'austria', 'Austria', 'at'),
    (51, 'armenia', 'Armenia', ''),
    (56, 'belgium' 'Belgium', 'be'),
    (68, 'bolivia', 'Bolivia', 'bo'),
    (76, 'brazil', 'Brazil', 'br'),
    (100, 'bulgaria', 'Bulgaria', 'bu'),
    (124, 'canada', 'Canada', 'ca'),
    (156, 'china', 'China', 'cn'),  # <--  ???
    (158, 'china', 'China', 'cn'),  # <--  ???
    (191, 'croatia', 'Croatia', ''),
    (192, 'cuba', 'Cuba', ''),
    (210, 'ethiopia', 'Ethiopia', 'et'),
    (246, 'finland', 'Finland', 'fi'),
    (250, 'france', 'France', 'fr'),
    (268, 'georgia', 'Georgia', ''),
    (276, 'germany', 'Germany', 'de'),
    (300, 'greece', 'Greece', 'gr'),
    (320, 'guatemala', 'Guatemala', ''),
    (356, 'india', 'India', 'in'),
    (364, 'iran', 'Iran', ''),
    (372, 'ireland', 'Ireland', 'ie'),
    (376, 'israel', 'Israel', 'is'),
    (380, 'italy', 'Italy', 'it'),
    (392, 'japan', 'Japan', 'jp'),
    (398, 'kasakhstan', 'Kasakhstan', ''),
    (450, 'madagascar', 'Madagascar', ''),
    (458, 'malaysia', 'Malaysia', 'my'),
    (484, 'mexico', 'Mexico', 'mx'),
    (496, 'mongolia', 'Mongolia', ''),
    (504, 'morocco', 'Morocco', ''),
    (508, 'mozambique', 'Mozambique', ''),
    (516, 'namibia', 'Namibia', ''),
    (566, 'nigeria', 'Nigeria', ''),
    (578, 'norway', 'Norway', 'no'),
    (586, 'pakistan', 'Pakistan', 'pk'),
    (604, 'peru', 'Peru', 'pe'),
    (616, 'poland', 'Poland', 'pl'),
    (620, 'portugal', 'Portugal', 'pt'),
    (643, 'russia', 'Russia', 'ru'),
    (682, 'saudi-arabia', 'Saudi Arabia', ''),
    (704, 'vietnam', 'Vietnam', ''),
    (705, 'slovenia', 'Slovenia', ''),
    (710, 'south-africa', 'South Africa', 'za'),
    (716, 'zimbabwe', 'Zimbabwe', ''),
    (724, 'spain', 'Spain', 'es'),
    (736, 'sudan', 'Sudan', ''),
    (752, 'sweden', 'Sweden', 'sv'),
    (756, 'switzerland', 'Switzerland', 'ch'),
    (792, 'turkey', 'Turkey', 'tr'),
    (788, 'tunisia', 'Tunisia', ''),
    (804, 'ukraine', 'Ukraine', ''),
    (807, 'macedonia', 'Macedonia', ''),
    (818, 'egypt', 'Egypt', ''),
    (840, 'usa', 'United States', 'us'),
    (858, 'uruguay', 'Uruguay', 'ur'),
    (862, 'venezuela', 'Venezuela', 've'),
    (891, 'yugoslavia', 'Yugoslavia', ''),
    (894, 'zambia', 'Zambia', ''),
)
