
# TODO: clean up names, and translate for German version.

# ID, slug, name, ???, ???, ???
#
# --> maybe add an individual description string to some.

COLOR_DATA = (
    (1, 'beige', 'beige'),
    (2, 'blue', 'blue'),
    (3, 'brown', 'brown'),
    (4, 'yellow', 'yellow'),
    (5, 'grey', 'grey'),
    (7, 'green', 'green'),
    (8, 'white', 'white'),
    (9, 'pink', 'pink'),
    (10, 'red', 'red'),
    (11, 'black', 'black'),
    (12, 'white', 'white'),
)
CLASSIFICATION_DATA = (
    (0, 'amazonite - granite', 'amazonite-granite'),
    (0, 'foidolite', 'foidolite'),
    (0, 'hornblende-amphibolite', 'hornblende-amphibolite'),
    (0, 'iron ore', 'iron ore'),
    (0, 'marble-onyx', 'marble-onyx'),
    (0, 'mikrolin-quatrz -phyllite', 'mikrolin-quatrz-phyllite'),
    (0, 'n/a', 'n/a'),
    (0, 'n.a', 'n/a'),
    (0, 'orbicular granite', 'orbicular granite'),
    (0, 'orthoklase - quartz - phyllite', 'orthoklase-quartz-phyllite'),
    (0, 'quartz -phyllite', 'quartz-phyllite'),
    (0, 'phyllite', 'phyllite'),
    (0, 'sodalite-syenite', 'sodalite-syenite'),
    (0, 'schist', 'schist'),
    (0, 'serizite-quatrz-phyllite', 'serizite-quatrz-phyllite'),
    (0, 'sodalithe-gneiss', 'sodalithe-gneiss'),
    (0, 'sodalithe-syenite', 'sodalithe-syenite'),
    (2, 'anhydrite', 'anhydrite'),
    (3, 'anorthosite', 'anorthosite'),
    (4, 'aplite', 'aplite'),
    (5, 'basalt', 'basalt'),
    (6, 'charnockite', 'charnockite'),
    (8, 'cordierite', 'cordierite'),
    (9, 'diabase', 'diabase'),
    (10, 'diorite', 'diorite'),
    (13, 'gabbro', 'gabbro'),
    (14, 'gneiss', 'gneiss'),
    (15, 'granite', 'granite'),
    (17, 'granodiorite', 'granodiorite'),
    (18, 'granulite', 'granulite'),
    (19, 'hornfels', 'hornfels'),
    (20, 'limestone', 'limestone'),
    (21, 'conglomerate', 'conglomerate'),
    (22, 'lamprophyre', 'lamprophyre'),
    (23, 'lava', 'lava'),
    (25, 'marble', 'marble'),
    (26, 'metatexite', 'metatexite'),
    (27, 'migmatite', 'migmatite'),
    (30, 'monzonite', 'monzonite'),
    (32, 'norite', 'norite'),
    (33, 'ophicalcite', 'ophicalcite'),
    (35, 'orthogneiss', 'orthogneiss'),
    (37, 'paragneiss', 'paragneiss'),
    (38, 'pegmatite', 'pegmatite'),
    (39, 'porphyry', 'porphyry'),
    (41, 'quartzite', 'quartzite'),
    (42, 'rhyolite', 'rhyolite'),
    (43, 'sandstone', 'sandstone'),
    (44, 'slate', 'slate'),
    (46, 'serpentinite', 'serpentinite'),
    (48, 'soapstone', 'soapstone'),
    (50, 'spessartite', 'spessartite'),
    (51, 'syenite', 'syenite'),
    (52, 'tonalite', 'tonalite'),
    (53, 'trachyte', 'trachyte'),
    (54, 'travertine', 'travertine'),
    (55, 'tuff', 'tuff'),
)
TEXTURE_DATA = (
    (0, 'coars'),
    (0, 'coarse'),
    (0, 'Coarse'),
    (0, 'coarse grain'),
    (0, 'coarse grained'),
    (0, 'coarse grain, veined'),
    (0, 'fine'),
    (0, 'Fine'),
    (0, 'fine grain'),
    (0, 'fine grained'),
    (0, 'fine grained, veined'),
    (0, 'fine grained, with plenty of large fossils'),
    (0, 'fine to medium'),
    (0, 'Fine grained'),
    (0, 'fine, medium'),
    (0, 'fine, veined'),
    (0, 'geädert'),
    (0, 'grob'),
    (0, 'medium'),
    (0, 'Medium'),
    (0, 'medium grain'),
    (0, 'medium grained'),
    (0, 'medium - coarse grain'),
    (0, 'n/a'),
    (0, 'veined'),
    (0, 'Veined'),
)
COUNTRY_DATA = (
    (24, 'angola', 'Angola'),
    (32, 'argentina', 'Argentina'),
    (36, 'australia', 'Australia'),
    (40, 'austria', 'Austria'),
    (51, 'armenia', 'Armenia'),
    (56, 'belgium' 'Belgium'),
    (68, 'bolivia', 'Bolivia'),
    (76, 'brazil', 'Brazil'),
    (100, 'bulgaria', 'Bulgaria'),
    (124, 'canada', 'Canada'),
    (156, 'china', 'China'),  # <--  ???
    (158, 'china', 'China'),  # <--  ???
    (191, 'croatia', 'Croatia'),
    (192, 'cuba', 'Cuba'),
    (210, 'ethiopia', 'Ethiopia'),
    (246, 'finland', 'Finland'),
    (250, 'france', 'France'),
    (268, 'georgia', 'Georgia'),
    (276, 'germany', 'Germany'),
    (300, 'greece', 'Greece'),
    (320, 'guatemala', 'Guatemala'),
    (356, 'india', 'India'),
    (364, 'iran', 'Iran'),
    (372, 'ireland', 'Ireland'),
    (376, 'israel', 'Israel'),
    (380, 'italy', 'Italy'),
    (392, 'japan', 'Japan'),
    (398, 'kasakhstan', 'Kasakhstan'),
    (450, 'madagascar', 'Madagascar'),
    (458, 'malaysia', 'Malaysia'),
    (484, 'mexico', 'Mexico'),
    (496, 'mongolia', 'Mongolia'),
    (504, 'morocco', 'Morocco'),
    (508, 'mozambique', 'Mozambique'),
    (516, 'namibia', 'Namibia'),
    (566, 'nigeria', 'Nigeria'),
    (578, 'norway', 'Norway'),
    (586, 'pakistan', 'Pakistan'),
    (604, 'peru', 'Peru'),
    (616, 'poland', 'Poland'),
    (620, 'portugal', 'Portugal'),
    (643, 'russia', 'Russia'),
    (682, 'saudi-arabia', 'Aaudi Arabia'),
    (704, 'vietnam', 'Vietnam'),
    (705, 'slovenia', 'Slovenia'),
    (710, 'south-africa', 'South Africa'),
    (716, 'zimbabwe', 'Zimbabwe'),
    (724, 'spain', 'Spain'),
    (736, 'sudan', 'Sudan'),
    (752, 'sweden', 'Sweden'),
    (756, 'switzerland', 'Switzerland'),
    (792, 'turkey', 'Turkey'),
    (788, 'tunisia', 'Tunisia'),
    (804, 'ukraine', 'Ukraine'),
    (807, 'macedonia', 'Macedonia'),
    (818, 'egypt', 'Egypt'),
    (840, 'usa', 'United States'),
    (858, 'uruguay', 'Uruguay'),
    (862, 'venezuela', 'Venezuela'),
    (891, 'yugoslavia', 'Yugoslavia'),
    (894, 'zambia', 'Zambia'),
)
