# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_foto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
