# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0003_auto_20160411_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
