# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0005_spams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spams',
            new_name='Spam',
        ),
    ]
