# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0006_auto_20160526_1028'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='userprofile',
            index_together=set([('user', 'city', 'country_name', 'is_blocked', 'is_deleted'), ('user', 'is_blocked', 'is_deleted')]),
        ),
    ]
