# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0007_auto_20160621_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pic',
            name='module',
            field=models.CharField(choices=[('profile', 'Profile'), ('projects', 'Projects'), ('stones', 'Stones'), ('stock', 'Stock'), ('groups', 'Groups'), ('pages', 'Pages')], db_index=True, default='profile', max_length=20),
        ),
        migrations.AlterField(
            model_name='pic',
            name='module_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterIndexTogether(
            name='pic',
            index_together=set([('module_id', 'module', 'is_blocked', 'is_deleted', 'created')]),
        ),
    ]
