# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0008_auto_20160621_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterIndexTogether(
            name='stock',
            index_together=set([('stone', 'created')]),
        ),
    ]
