# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0009_auto_20160621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='The name of your company.', max_length=100, verbose_name='Company name'),
        ),
    ]
