# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companydb', '0010_auto_20160621_1146'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='userprofile',
            index_together=set([('user', 'city', 'country_name', 'title_foto', 'is_blocked', 'is_deleted'), ('user', 'is_blocked', 'is_deleted')]),
        ),
    ]
