# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradeshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aumaid', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(default='', max_length=60)),
                ('aka', models.CharField(default='', max_length=255)),
                ('url', models.SlugField(default='', max_length=60)),
                ('city_name', models.CharField(default='', max_length=60)),
                ('country_name', models.CharField(default='', max_length=60)),
                ('begins', models.DateField(default=None, null=True)),
                ('ends', models.DateField(default=None, null=True)),
                ('keywords', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('web', models.CharField(default='', max_length=250)),
                ('contact', models.CharField(default='', max_length=250)),
                ('logo', models.CharField(default='', max_length=60)),
                ('ip', models.CharField(default='', max_length=15)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'tradeshows',
                'verbose_name': 'tradeshow',
                'ordering': ('begins',),
            },
        ),
    ]
