# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeshowdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tradeshow',
            index_together=set([('begins', 'ends')]),
        ),
    ]
