# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonedb', '0002_auto_20160621_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonename',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
