# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='article',
            index_together=set([('is_published', 'is_frontpage'), ('topic', 'is_published')]),
        ),
    ]
