# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mdpages', '0002_auto_20160621_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterIndexTogether(
            name='article',
            index_together=set([('is_published', 'is_frontpage', 'created'), ('topic', 'is_published', 'created')]),
        ),
    ]
